{{- $globalIngress := include "globalIngress" . | fromYaml }}
{{- $globalApp := include "globalApp" . | fromYaml }}
{{- if $globalIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ingress
  namespace: {{ $globalApp.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    {{- if $globalIngress.internal }}
    alb.ingress.kubernetes.io/scheme: internal
    {{- else }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- end }}
    {{- if $globalIngress.subnets }}
    alb.ingress.kubernetes.io/subnets: {{ $globalIngress.subnets }}
    {{- end }}
    {{- if and $globalIngress.certificate $globalIngress.certificate.arn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ tpl $globalIngress.certificate.arn . }}
    {{- end }}
    {{- if and $globalIngress.group $globalIngress.group.enabled }}
    alb.ingress.kubernetes.io/group.name: {{ $globalIngress.group.name }}
    {{- end }}
    {{- with $globalIngress.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ tpl $globalIngress.hostname . }}
    http:
      paths:
      - path: {{ $globalIngress.path }}
        pathType: {{ $globalIngress.pathType }}
        backend:
          service:
            name: {{ include "fullname" . }}
            port:
              number: {{ .Values.service.port }}
      {{- range $globalIngress.extraPaths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ include "fullname" $ }}-ext
            port:
              number: {{ .port }}
      {{- end }}
  {{- range $globalIngress.extraRules }}
  - host: {{ tpl .host $ }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .port }}
      {{- end }}
  {{- end }}
{{- end }}