{{- if .Values.serviceAccount.create }}
{{- $annotations := dict }}
{{- if .Values.serviceAccount.aws.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.aws.annotations }}
{{- end }}
{{- if .Values.serviceAccount.azure.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.azure.annotations }}
{{- end }}
{{- if .Values.serviceAccount.gcp.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.gcp.annotations }}
{{- end }}
{{- if .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.annotations }}
{{- end }}
{{- $globalApp := include "globalApp" . | fromYaml }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  namespace: {{ $globalApp.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}